service: gcsmanagerapi
runtime: nodejs20
env: standard
env_variables:
  DBHOST: ""
  DBNAME: "gcsmanagerapi"
  DBUSER: ""
  DBPASSWORD: ""
  DBENGINE: "postgresql"
  APPLICATION_NAME : "gcsmanagerapi"
  APPLICATION_TITLE : "GCS Manager API"
  APPLICATION_PORT : "8080"
  PROJECT : "lv-saas"

