service: gcsmanagerapi
runtime: nodejs16
env: standard
env_variables:
  DBHOST: "34.67.143.103"
  DBNAME: "gcsmanagerapi"
  DBUSER: "nodeuser"
  DBPASSWORD: "RotiKeju98*"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "gcsmanagerapi"
  APPLICATION_TITLE : "GCS Manager API"
  APPLICATION_PORT : "8080"
  PROJECT : "huda-playground"

